### ISSUE TITLE
Is there any way to also block requests from Shodan?

### ISSUE THREAD

**Issue by AnderssonPeter** [jpxd/torblock#3]
Is there any way to also block requests from Shodan?
If not could you create a polygon for that?

**Comment by jpxd** [comment]
Hi, thanks for your suggestion! This plugin blocks requests from the Tor network by using the public list of Tor exit node IPs at https://check.torproject.org/exit-addresses. Unfortunately, there is currently no official list of Shodan IPs that could be used for blocking. One option would be to create your own list in the same format as the Tor list and overwrite the config setting 'AddressListURL', but this would require manual effort to keep the list updated.

**Comment by AnderssonPeter** [comment]
@jpxd looks like there is a list [here](https://github.com/SilvrrGIT/IP-Lists/blob/master/shodan) that's updated regularly, but it's in the incorrect format
